### ISSUE TITLE
EOL NOTICE FOR YOUTUBE-DL BASED VERSIONS / youtube-dlフォーク版の廃止について

### ISSUE THREAD

**Issue by nao20010128nao** [ytdl-patched/ytdl-patched#1]
# EOL NOTICE FOR YOUTUBE-DL BASED VERSIONS
I'll announce EOL schedule for youtube-dl-fork version of ytdl-patched.

## What's going on? Will this project reach its end?
No, ytdl-patched itself continues. But youtube-dl based version ("old version") will get replaced by yt-dlp based version ("new version").

## Timeline and Schedule
All dates are written in `YYYY/MM/DD`, which imitates youtube-dl/yt-dlp's version notation. Timezone is `UTC+9:00 (no DST)`. Everything is estimate or plan and subject to change.

- `2021/07/10`~`2021/08/15`
  - Old version goes into "maintain phase". This means that new features/extractors will not be implemented except merging and vulnerability or emergency fix.
  - New version will continue development and sometimes merged from upstream. Some forgotten features/extractors may be migrated.
  - Please help testing new version in this period.
- `2021/08/16`~
  - New version replaces old version. Old version will no longer be maintained.
  - Doing `-U` or `brew upgrade` should normally upgrade to new version.
  	- If the version you're trying to upgrade from is old enough (before `2021.05.01.*`), please download again.
  - Scripts calling ytdl-patched directly will break after EOL because yt-dlp has changed its module name. See below.

## yt-dlp based version? Where can I find it?
For built binaries, please download [Pre-release](https://github.com/ytdl-patched/ytdl-patched/releases) versions. This is what you're looking for.
For source code, you can find it at [ytdlp](https://github.com/ytdl-patched/ytdl-patched/tree/ytdlp) branch of this repo.

## What should I do?
For most users, you don't have to do anything. Just wait.

For advanced users, please help testing new version. There could be flaws and bugs caused by heavy modifications. Doing `-U` on new version should work.

For developers, please update imports and something related. `youtube_dl` has been changed to `yt_dlp` including child modules.

# youtube-dlフォーク版の廃止について
youtube-dlベース版ytdl-patchedの開発終了スケジュールについて案内します。

## 具体的には何をするのか
youtube-dlベース版("旧バージョン")の開発を終了し、yt-dlpベース("新バージョン")で新たに作り直します。

## スケジュール
全ての日付は予定であり、場合によっては前後することがあります。

- `2021/07/10`~`2021/08/15`
  - 旧バージョンは保守フェーズに移行します。原則としてマージ以外で新機能やウェブサイトの追加等は行いませんが、脆弱性などの大至急の修正を要するものについてはこの限りではありません。
  - 新バージョンは開発を継続します。たまーにyt-dlpからマージもします。旧バージョンからの移植を忘れている機能については、移植されます。
  - この期間に新バージョンを使って頂き、バグ等があればご報告下さい。
- `2021/08/16`~
  - この日付以降、新バージョンのみを提供します。旧バージョンは完全に開発を終了します。
  - `-U`オプションで新バージョンにアップデートできるはずです。
    - が、アップデート前のバージョンが古すぎる場合(特に`2021.05.01.*`以前)、アップデータは動作しない可能性があります。その場合はお手数をおかけしますが再ダウンロードをお願いします。
  - ytdl-patchedを直接呼び出しているスクリプト類は動作しなくなります。(下記参照)

## 新バージョンはどこにありますか?
新バージョンは[ReleasesのPre-release](https://github.com/ytdl-patched/ytdl-patched/releases)がこれに当たります。ビルド済みのバイナリはそこにあります。皆さんがお探しのものはここだろうと思います。    
ソースコードについては、このリポジトリの[ytdlp](https://github.com/ytdl-patched/ytdl-patched/tree/ytdlp)にあります。

## 何かする必要はありますか?
ほとんどの利用者は何もする必要はありません。

使い慣れた方々には、可能であれば新バージョンを使って頂き、テストにご協力下さい。様々な改造をしているため、何らかの不具合がある可能性があります。`-U`で新バージョン同士のアップデートが可能です。

開発者の方でスクリプトなどから直接呼び出している場合、yt-dlp側でmoduleの置き換えがあった影響でimport行などは置き換える必要があります。

**Comment by Lesmiscore** [comment]
I have vaccinated at Aug., 14th, so deprecation of youtube-dl based version may delay.

**Comment by Lesmiscore** [comment]
Please run with `-U` several times until it says `ytdl-patched is up to date`.
![Selection_001](https://user-images.githubusercontent.com/10355528/129465475-71efefb5-4527-4219-9423-4250a27fea03.png)
