### ISSUE TITLE
Self-updater error

### ISSUE THREAD

**Issue by haccy** [ytdl-patched/ytdl-patched#10]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Self-updater command `youtube-dl-red.exe -U` failed.

```
>youtube-dl-red.exe -U
Current version 2021.11.22.1637586417; Build Hash f68a2cce2bc083f64897321dbce4ef4e9a7e8d6b3c5f6a9252aee43d9579c9c3
Updating to version 2021.11.23.1637654551 ...
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 24, in <module>
  File "yt_dlp\__init__.py", line 824, in main
  File "yt_dlp\__init__.py", line 795, in _real_main
  File "yt_dlp\update.py", line 184, in run_update
  File "yt_dlp\update.py", line 153, in get_bin_info
KeyError: 'exe_red_64'
[13704] Failed to execute script '__main__' due to unhandled exception!
```

### Verbose log

```shell
[debug] Encodings: locale cp932, fs utf-8, out utf-8, err utf-8, pref cp932
[debug] ytdl-patched version 2021.11.22.1637586417  (exe_red)
[debug]      from commit 1e5182ae9
[debug]      based on 849d699a8
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.7.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
```

**Comment by Lesmiscore** [comment]
Thank you for reporting. The bug is fixed, but it requires downloading new version (which will be available in 10 minutes or so) to work again.
Sorry for inconvenience.
