### ISSUE TITLE
Using `-f best` gives error and does not start

### ISSUE THREAD

**Issue by Dluke77lnx** [ytdl-patched/ytdl-patched#11]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When trying to download a playlist or a whole site, from this release, i get error in python lines.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '-o', '/mnt/500gb/youdown/KaraOK/%(uploader)s/%(title)s.%(ext)s', '-f', 'best', '-ciw', '--min-filesize', '2M', '--max-filesize', '60M', '--download-archive', '/mnt/500gb/youdown/Database_singolo.txt', 'https://www.youtube.com/channel/UCpSayIQ4A7-1sUjgXZg4-Fw/videos']
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 24, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 860, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 159, in _real_main
TypeError: str.join() takes exactly one argument (3 given)
```

**Comment by Lesmiscore** [comment]
That seems a bug introduced in yt-dlp. ~~Consider reporting it in yt-dlp.~~ Right now pasted in Discord

```
$ ./yt-dlp.sh -f best -s google.com -v
[debug] Command-line config: ['-f', 'best', '-s', 'google.com', '-v']
Traceback (most recent call last):
  File "/home/lesmi/yt-dlp/yt_dlp/__main__.py", line 19, in <module>
    yt_dlp.main()
  File "/home/lesmi/yt-dlp/yt_dlp/__init__.py", line 827, in main
    _real_main(argv)
  File "/home/lesmi/yt-dlp/yt_dlp/__init__.py", line 140, in _real_main
    warnings.append('.\n         '.join(
TypeError: str.join() takes exactly one argument (3 given)
```

_nitpick: I don't recommend you to use `-f best` unless there's any special reason for you_
