### ISSUE TITLE
is it possible to "download" premium video from abema?

### ISSUE THREAD

**Issue by vikkstar12** [ytdl-patched/ytdl-patched#12]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have an premium account from abema and trying to download premium shows frome there, is it possible? before i know this repo, i'm using [yuu](https://github.com/noaione/yuu) to download and it works with premium account... But now it doesnt work anymore  and the repo didn't get update a very long time. I'm hopeless to find a tools to download the premium shows.

### Verbose log

```shell
[debug] Command-line config: ['https://abema.tv/video/episode/90-1602_s2_p11', '--username', 'PRIVATE', '--password', 'PRIVATE', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] ytdl-patched version 2021.12.28.1640651155  (exe_red)
[debug]      from commit de2674ec2
[debug]      based on 45d86abeb
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.7.9 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 2021-08-04-git-3b298640e1-full_build-www.gyan.dev (setts), ffprobe 2021-08-04-git-3b298640e1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.28.1640651155, Current version: 2021.12.28.1640651155
ytdl-patched is up to date (2021.12.28.1640651155)
[debug] [AbemaTV] Extracting URL: https://abema.tv/video/episode/90-1602_s2_p11
[AbemaTV] Authorizing
[AbemaTV] [debug] Fetching webpage from https://api.abema.io/v1/users
[AbemaTV] 90-1602_s2_p11: Downloading webpage
[AbemaTV] [debug] Fetching webpage from https://abema.tv/video/episode/90-1602_s2_p11
[AbemaTV] 90-1602_s2_p11: Checking playability
[AbemaTV] [debug] Fetching webpage from https://api.abema.io/v1/video/programs/90-1602_s2_p11
ERROR: [AbemaTV] 90-1602_s2_p11: Premium stream is not supported
  File "yt_dlp\extractor\common.py", line 631, in extract
  File "yt_dlp\extractor\abematv.py", line 308, in _real_extract

[debug] Cleaning up 3 streams
```

**Comment by Lesmiscore** [comment]
For now, no. As I don't have premium account, I need one for investigating how to download premium videos.
Please let me know if you're willing to share account credential details.

**Comment by vikkstar12** [comment]
i mean you can try free trial 2 weeks in their android apk. Registering an account really easy but to subscribe you need and android smartphone :D

**Comment by Lesmiscore** [comment]
Okay, will try digging in, but I can't provide any ETA for this.
Are you hurrying for doing this?

**Comment by Lesmiscore** [comment]
Implemented login. You can use `--username` and `--password` or netrc in upcoming version. Let me know if it works.

**Comment by vikkstar12** [comment]
Would love and try it when it's released :D

**Comment by Lesmiscore** [comment]
It's already here, just run update now

**Comment by vikkstar12** [comment]
not working it seems.

> [debug] Command-line config: ['https://abema.tv/video/episode/90-1602_s2_p11', '--username', 'PRIVATE', '--password', 'PRIVATE', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] ytdl-patched version 2021.12.31.1640929671  (exe_red)
[debug]      from commit 38ba49ceb
[debug]      based on 11aa91a12
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.7.9 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 2021-08-04-git-3b298640e1-full_build-www.gyan.dev (setts), ffprobe 2021-08-04-git-3b298640e1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.31.1640929671, Current version: 2021.12.31.1640929671
ytdl-patched is up to date (2021.12.31.1640929671)
[AbemaTV] Authorizing
[AbemaTV] [debug] Fetching webpage from https://api.abema.io/v1/users
[AbemaTV] Fetching media token
[AbemaTV] [debug] Fetching webpage from https://api.abema.io/v1/media/token?osName=android&osVersion=6.0.1&osLang=ja_JP&osTimezone=Asia%2FTokyo&appId=tv.abema&appVersion=3.27.1
[AbemaTV] Logging in
[AbemaTV] [debug] Fetching webpage from https://api.abema.io/v1/auth/user/email
ERROR: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1411, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1491, in __extract_info
  File "yt_dlp\extractor\common.py", line 630, in extract
  File "yt_dlp\extractor\common.py", line 530, in initialize
  File "yt_dlp\extractor\abematv.py", line 220, in _real_initialize
  File "yt_dlp\extractor\abematv.py", line 239, in _login
  File "yt_dlp\extractor\common.py", line 1019, in _download_json
  File "yt_dlp\extractor\common.py", line 997, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 785, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 752, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 2843, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3733, in urlopen
  File "urllib\request.py", line 523, in open
  File "urllib\request.py", line 1280, in do_request_
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.

>[debug] Cleaning up 2 streams

**Comment by Lesmiscore** [comment]
oops, fixed
soon you will get fix (usually 10 minutes)

**Comment by vikkstar12** [comment]
the error is different from the previous one.

> [debug] Command-line config: ['https://abema.tv/video/episode/90-1602_s2_p11', '--username', 'PRIVATE', '--password', 'PRIVATE', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] ytdl-patched version 2021.12.31.1640931630  (exe_red)
[debug]      from commit 782943042
[debug]      based on 11aa91a12
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.7.9 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 2021-08-04-git-3b298640e1-full_build-www.gyan.dev (setts), ffprobe 2021-08-04-git-3b298640e1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.31.1640931630, Current version: 2021.12.31.1640931630
ytdl-patched is up to date (2021.12.31.1640931630)
[AbemaTV] Authorizing
[AbemaTV] [debug] Fetching webpage from https://api.abema.io/v1/users
[AbemaTV] Fetching media token
[AbemaTV] [debug] Fetching webpage from https://api.abema.io/v1/media/token?osName=android&osVersion=6.0.1&osLang=ja_JP&osTimezone=Asia%2FTokyo&appId=tv.abema&appVersion=3.27.1
[AbemaTV] Logging in
[AbemaTV] [debug] Fetching webpage from https://api.abema.io/v1/auth/user/email
ERROR: [AbemaTV] 90-1602_s2_p11: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 752, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 2843, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3733, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

[debug] Cleaning up 2 streams

**Comment by Lesmiscore** [comment]
Update again in 10 minutes. I wasn't tested it well

**Comment by vikkstar12** [comment]
Omg its worked!!! Thank you so much!!

**Comment by Lesmiscore** [comment]
Worked!? Glad to hear that.

Closing this as resolved. Thanks for your request.

Feel free to open a new issue once you get problems.

**Comment by vikkstar12** [comment]
once again thank you!! 👍  ![](https://puu.sh/IzBDU.jpg) 

though Abema keep spamming me email when i download haha telling me a new login detected lol
