### ISSUE TITLE
[TwitCasting] Notices for split archives retrieval changes

### ISSUE THREAD

**Issue by Lesmiscore** [ytdl-patched/ytdl-patched#15]
# [TWITCASTING] NOTICES FOR SPLIT ARCHIVES RETRIEVAL CHANGES
I'll be announcing planned changes about TwitCasting's split archives.

## Background
For downloading TwitCasting's live archive, it is known that they sometimes split archive 1 hour each. (see https://github.com/yt-dlp/yt-dlp/issues/382)

For this problem, ytdl-patched is able to find other splits, and downloaded by using `-f hls-N` option. You can also join them as one video using `-f joinall`.
However, this behavior does not conform with the `format` concept of youtube-dl/yt-dlp/ytdl-patched.

As yt-dlp introduced support for joining `multi_video` playlists in 3b603dbdf139efe187f961dbe8b1b24ba16ae194, the aforementioned method is now completely legacy.
So I decided to transition to the new method using `multi_video`.

## Timeline and Schedule
All dates are written in `YYYY/MM/DD`, which imitates youtube-dl/yt-dlp's version notation. Timezone is `UTC+9:00 (no DST)`. Everything is estimate or plan and subject to change.

- `2022/01/13`~`2022/01/31`
  - Both method are available, and you can opt in for using `multi_video` method by `--extractor-args twitcasting:archive_mode=multi_video --concat-playlist multi_video` (no `-f` needed)
    - You'll see a warning about this.
  - However, the default behavior is still old one which uses `-f`
- `2022/02/01`~`2022/02/15`
  - Default method is changed to the new one in this period. 
  - You can still rollback to old one using `--extractor-args twitcasting:archive_mode=formats -f joinall`
- `2022/02/15`~
  - The old method will be removed. It will no longer be available.

## What should I do?
Only people who are using ytdl-patched to download whole TC archives applies.
Please keep your eyes to this issue, as I'll keep posting updates as needed.

**Comment by afterdelight** [comment]
wtf
