### ISSUE TITLE
[MySpass] ERROR: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by lord-of-blood** [ytdl-patched/ytdl-patched#16]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

NoneType Error occured when downloading a video.

### Verbose log

```shell
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.9.1 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.3
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [MySpass] Extracting URL: https://www.myspass.de/shows/tvshows/tv-total/Novak-Puffovic-bei-bester-Laune--/44996/
[MySpass] 44996: Downloading XML
ERROR: 'NoneType' object has no attribute 'groups'
Traceback (most recent call last):
  File "C:\...\Roaming\Python\Python39\site-packages\yt_dlp\YoutubeDL.py", line 1367, in wrapper
    return func(self, *args, **kwargs)
  File "C:\...\Roaming\Python\Python39\site-packages\yt_dlp\YoutubeDL.py", line 1437, in __extract_info
    ie_result = ie.extract(url)
  File "C:\...\Roaming\Python\Python39\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "C:\...\Roaming\Python\Python39\site-packages\yt_dlp\extractor\myspass.py", line 38, in _real_extract
    for group in re.search(r'/myspass2009/\d+/(\d+)/(\d+)/(\d+)/', video_url).groups():
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by Lesmiscore** [comment]
Report it to yt-dlp with **verbose log from genuine yt-dlp**.
That extractor hasn't been customized.
