### ISSUE TITLE
[TwitCastingLive] m3u8 playlist extraction failing for password protected archived streams

### ISSUE THREAD

**Issue by AlphaCentauri** [ytdl-patched/ytdl-patched#17]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

N/A

### Description

Unable to download archived TwitCasting streams that contain a password. Extractor fails to obtain the m3u8 playlist properly. I have tested with and without `-f joinall` after I saw your announcement regarding split-archive support.

--

Side note, this is somewhat of a continuation of the issue I opened earlier on the primary yt-dlp repostory (https://github.com/yt-dlp/yt-dlp/issues/2792), but I am unable to download streams even with the URL extraction update you added here and merged into yt-dlp.

### Verbose log

```shell
[debug] Command-line config: ['https://twitcasting.tv/rurufuhizuki/movie/721103571', '-N', '20', '-vU', '--video-password', 'PRIVATE', '-f', 'joinall']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] ytdl-patched version 2022.02.15.1644937342  (zip)
[debug]      from commit 95fd95585
[debug]      based on 812283199
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-28-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.3.1 (fdk)
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.15.1644937342, Current version: 2022.02.15.1644937342
ytdl-patched is up to date (2022.02.15.1644937342)
[debug] [TwitCasting] Extracting URL: https://twitcasting.tv/rurufuhizuki/movie/721103571
[TwitCasting] 721103571: Downloading webpage
[TwitCasting] [debug] Fetching webpage from https://twitcasting.tv/rurufuhizuki/movie/721103571
[TwitCasting] 721103571: Downloading live info
[TwitCasting] [debug] Fetching webpage from https://twitcasting.tv/streamserver.php?target=rurufuhizuki&mode=client
ERROR: [TwitCasting] 721103571: Failed to get m3u8 playlist; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "./youtube-dl/yt_dlp/extractor/common.py", line 649, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/yt_dlp/extractor/twitcasting.py", line 149, in _real_extract
    raise ExtractorError('Failed to get m3u8 playlist')

[debug] Cleaning up 2 streams
```

**Comment by Lesmiscore** [comment]
It's working with the sample I have. Please re-check if the password is correct.

**Comment by AlphaCentauri** [comment]
The password was fine, it seemed to be an issue with possibly either my version of python or ffmpeg. Finally got a chance to install it on a different computer at home running more bleeding edge versions of the aforementioned packages and the same sample as above downloaded just fine.
Closing.
