### ISSUE TITLE
ABOUT PLANNED 2 MAJOR BREAKING CHANGES

### ISSUE THREAD

**Issue by Lesmiscore** [ytdl-patched/ytdl-patched#19]
# ABOUT PLANNED 2 MAJOR BREAKING CHANGES
I'll be announcing planned the following 2 major breaking changes:
- Changing default output filename to what yt-dlp uses
- Binary filename change

## Changing default output filename to what yt-dlp uses

As README says:

> * **Some features/behaviors are reverted**: Some changes in yt-dlp has been reverted to match that of youtube-dl.
>     * Output filename template. In yt-dlp, it was `%(title)s [%(id)s].%(ext)s`. But ytdl-patched uses `%(title)s-%(id)s.%(ext)s`.

This will be changed to what currently it is in yt-dlp, say `%(title)s [%(id)s].%(ext)s`.
It was to keep consistent between before and after #1 takes places. In order to reduce maintenance work in the future, it will be done.
You can still use old one using `-o "%(title)s-%(id)s.%(ext)s"`, and transition to new one with `-o "%(title)s [%(id)s].%(ext)s"`.

## Binary filename change
Since ytdl-patched is "modified youtube-dl just for myself", binary name is just `youtube-dl`. Since it clashes with the command line application with the same name, it will be renamed to `ytdl-patched`, for everything (Homebrew, Releases, tar.gz etc.)

## Scheduled Timelines
All dates are written in `YYYY/MM/DD`. Timezone is UTC+9:00 (no DST) otherwise noted. Everything is estimate or plan and subject to change without notice.

* (In few days)
  * Updater will be changed to support new binary filename, `ytdl-patched`. At that time, uploaded files will still have `youtube-dl`
* 2022/04/10
  * Changing default output filename will be done. After the date, you'll get same filename as yt-dlp, unless you have `-o` set in config or command line.
* 2022/04/15 ~ 2022/04/17
  * Preparation and tests for renaming binary filenames may be done.
* 2022/04/18
  * Binary filename change is expected to be done at the day.

**Comment by afterdelight** [comment]
Looks nice

**Comment by afterdelight** [comment]
will the execution command changed to "ytdl-patched  xxx"?
and
will the installation folder inside python folder changed to "ytdl_patched"

**Comment by afterdelight** [comment]
MICE
