### ISSUE TITLE
[Feature Request] RPC

### ISSUE THREAD

**Issue by Lesmiscore** [ytdl-patched/ytdl-patched#2]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Implement RPC to control downloader

possibly over HTTP, but maybe WebSocket

do this after misskey

**Comment by Dibbyo456** [comment]
Is it completed.?
