### ISSUE TITLE
option to disable .lock file

### ISSUE THREAD

**Issue by afterdelight** [ytdl-patched/ytdl-patched#21]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When i closed the cmd command prompt on windows the .lock file is not deleted and I cant resume the download process because of the .lock file. I must pressed Ctrl+C to cancel download so the lock file to disappear. The original yt-dlp doesnt have this bug. Plase add argument option to disable .lock file as this is kind of annoying. thx!

**Comment by Lesmiscore** [comment]
Add `--no-lock` to config file. This is created by default to allow running simultaneously with the same playlist.

**Comment by afterdelight** [comment]
ok ty
