### ISSUE TITLE
Add afreecatv VODs page support

### ISSUE THREAD

**Issue by afterdelight** [ytdl-patched/ytdl-patched#22]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Add afreecatv user vods pages support

Example links:
https://bj.afreecatv.com/ryuryu24/vods
https://bj.afreecatv.com/ryuryu24/vods/balloonclip
https://bj.afreecatv.com/ryuryu24/vods/clip
https://bj.afreecatv.com/ryuryu24/vods/highlight
https://bj.afreecatv.com/ryuryu24/vods/list
https://bj.afreecatv.com/ryuryu24/vods/myclip
https://bj.afreecatv.com/ryuryu24/vods/normal
https://bj.afreecatv.com/ryuryu24/vods/review
https://bj.afreecatv.com/ryuryu24/vods/user

**Comment by Lesmiscore** [comment]
Go to yt-dlp
