### ISSUE TITLE
91porn.com

### ISSUE THREAD

**Issue by afterdelight** [ytdl-patched/ytdl-patched#23]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Indonesia

### Example URLs

channel:
http://91porn.com/uvideos.php?UID=bed1ajXJasOYYN4B9v38lay3G0BF6XSnFOSd7FgalAjopOlyOw&type=public
single link:
http://91porn.com/view_video.php?viewkey=051a5a363acfd11e3e69

### Description

Add scraping support for both user channel  and single link for 91porn.com

### Verbose log

```shell
E:\scraper and downloader\91porn>youtube-dl -v http://91porn.com/view_video.php?viewkey=051a5a363acfd11e3e69
[debug] Command-line config: ['-v', 'http://91porn.com/view_video.php?viewkey=051a5a363acfd11e3e69']
[debug] User config "C:\Users\X\AppData\Roaming\yt-dlp\config": ['--continue', '--format-sort', 'vbr,abr', '--http-chunk-size', '1M', '--buffer-size', '16K', '--sub-lang', 'english', '--embed-metadata', '--abort-on-unavailable-fragment', '-o', '%(title)s [%(id)s].%(ext)s', '--ffmpeg-location', 'D:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe', '--no-lock']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] ytdl-patched version 2022.03.08.1
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.4 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: "D:\Program Files\ffmpeg\bin\ffmpeg.exe" -bsfs
[debug] Checking exe version: "D:\Program Files\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg 2022-03-28-git-5ee198f9aa-essentials_build-www.gyan.dev (setts), ffprobe 2022-03-28-git-5ee198f9aa-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [91porn] Extracting URL: http://91porn.com/view_video.php?viewkey=051a5a363acfd11e3e69
[91porn] 051a5a363acfd11e3e69: Downloading webpage
[91porn] [debug] Fetching webpage from http://91porn.com/view_video.php?viewkey=051a5a363acfd11e3e69
ERROR: [91porn] 051a5a363acfd11e3e69: Unable to extract title; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "c:\python\python39\lib\site-packages\yt_dlp\extractor\common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "c:\python\python39\lib\site-packages\yt_dlp\extractor\porn91.py", line 38, in _real_extract
    title = self._search_regex(
  File "c:\python\python39\lib\site-packages\yt_dlp\extractor\common.py", line 1292, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)


E:\scraper and downloader\91porn>pause
Press any key to continue . . .
```

**Comment by Lesmiscore** [comment]
Go to yt-dlp.
