### ISSUE TITLE
Add option to prevent/restrict redirection

### ISSUE THREAD

**Issue by ruizlenato** [ytdl-patched/ytdl-patched#33]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Many websites embed media in sometimes annoying ways, for example: A twitter post may link to a website and yt-dlp automatically redirects to the link that is in the tweet

I use embedded yt-dlp and sometimes unintentionally download videos from other websites because a tweet had a link

### Verbose log

```shell
❯ yt-dlp https://twitter.com/Metropoles/status/1529224356643098624
[twitter] 1529224356643098624: Downloading guest token
[twitter] 1529224356643098624: Downloading JSON metadata
[generic] BHM6AAd: Requesting header
[redirect] Following redirect to https://www.metropoles.com/colunas/janela-indiscreta/doutor-peludo-medico-divulga-sexo-com-pacientes-dentro-de-consultorio
[generic] doutor-peludo-medico-divulga-sexo-com-pacientes-dentro-de-consultorio: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] doutor-peludo-medico-divulga-sexo-com-pacientes-dentro-de-consultorio: Downloading webpage
[generic] doutor-peludo-medico-divulga-sexo-com-pacientes-dentro-de-consultorio: Extracting information
[download] Downloading playlist: Doutor Peludo: médico divulga sexo com pacientes dentro de consultório
[generic] playlist Doutor Peludo: médico divulga sexo com pacientes dentro de consultório: Downloading 1 videos
[download] Downloading video 1 of 1
[JWPlatform] nzSKSIsk: Downloading JSON metadata
```

**Comment by Lesmiscore** [comment]
As the goal for this project isn't to rebellion yt-dlp, let's see how they do...

Related: https://github.com/yt-dlp/yt-dlp/issues/2044

**Comment by afterdelight** [comment]
jjkkkk

**Comment by afterdelight** [comment]
why did u closet this?
