### ISSUE TITLE
What to Use Instead of --hls-prefer-native, and --hls-prefer-ffmpeg

### ISSUE THREAD

**Issue by TellyHub** [ytdl-patched/ytdl-patched#42]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

What to Use Instead of --hls-prefer-native, and --hls-prefer-ffmpeg and By Using Above Showing No such File or directory Found 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
What to Use Instead of --hls-prefer-native, and --hls-prefer-ffmpeg

Ernos:No Such File or Directory Found
```

**Comment by Lesmiscore** [comment]
Show the situation, by supplying verbose log

**Comment by afterdelight** [comment]
yeah post the full verbose
