### ISSUE TITLE
self update error

### ISSUE THREAD

**Issue by haccy** [ytdl-patched/ytdl-patched#43]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

A release does not include '_update_spec' asset.
So cannot read update info.

https://github.com/ytdl-patched/ytdl-patched/blob/859bacacf57bbedef934edb6abfb02bf4223899a/yt_dlp/update.py#L109

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-U', '-v']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] ytdl-patched version 2022.07.17.1658029399  (exe_red)
[debug]      from commit bba706bcc
[debug]      based on e3e606de1
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python 3.7.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-8-g0c120f235a-20220714 (setts), ffprobe n5.0.1-8-g0c120f235a-20220714, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, WebSocketsWrapper-None, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/ytdl-patched/ytdl-patched/releases/latest
ERROR: Unable to obtain version info; Please try again later or Visit  https://github.com/ytdl-patched/ytdl-patched/releases/latest
```

**Comment by Lesmiscore** [comment]
yt-dlp's update code is getting complex over days :man_facepalming:
