### ISSUE TITLE
Can't understand between white & red.exe

### ISSUE THREAD

**Issue by bachig26** [ytdl-patched/ytdl-patched#52]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I just found this project of yt-dlp, which I'm questioning myself why just now should have found it sooner...LMAO.

My question as in title, I'm quite confused between the two version of `red` and `white`. as mentioned in the release notes that red is default to -U which i believe has the self updater. but when I looked through readme., both have the self updater function.

Please let me know what are the differences between them!!!

Thank you.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Lesmiscore** [comment]
Just a difference in icon. Others are all same

**Comment by afterdelight** [comment]
> Just a difference in icon. Others are all same

k
