### ISSUE TITLE
req help: cbs.com ERROR: fixed output name but more than one file to download

### ISSUE THREAD

**Issue by FredThompsonII** [ytdl-patched/ytdl-patched#76]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Would someone please tell me how to make this call so the file is downloaded without the error message? The only change I have made to arguments is using browser cookie instead of user and pass fields because ytdl-patched reports that is what must be currently done.

youtube-dl -cookies cbs.com_cookies.txt -o "Young Sheldon 0609 College Droputs and the Medford Miracle 1080p AAC 2.0 x264.mp4" "https://www.cbs.com/shows/video/U3ELqctyQXYmBrCMn49wnLBD_LPHknrV/"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-cookies', 'cbs.com_cookies.txt', '-o', 'Young Sheldon 0609 College Droputs and the Medford Miracle 1080p AAC 2.0 x264.mp4', 'https://www.cbs.com/shows/video/U3ELqctyQXYmBrCMn49wnLBD_LPHknrV/', '-vU']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg n5.1.2-9-g807afa59cc-20221208, ffprobe n5.1.2-9-g807afa59cc-20221208
[debug] Proxy map: {}
youtube-dl is up-to-date (2021.12.17)
ERROR: fixed output name but more than one file to download
```

**Comment by october262** [comment]
when i tried your test link, it says that the video is DRM protected.
